micronaut:
  server:
    port: 8084
  application:
    name: micronuatCassandraSample
cassandra:
  default:
    clusterName: 'Test Cluster'
    contactPoint: '0.0.0.0'
    datacenter: "datacenter1"
    keyspace: "store"
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
    sessionLimit: 20
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**